//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cashier.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery
    {
        public int Id { get; set; }
        public System.DateTime DTDelivery { get; set; }
        public int StatusId { get; set; }
        public int PaymentId { get; set; }
        public string Address { get; set; }
        public string PhoneClient { get; set; }
    
        public virtual DeliveryStatus DeliveryStatus { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
